platform :ios, '14.0'

install! 'cocoapods', :disable_input_output_paths => true

use_frameworks!

target 'Runner' do
  pod 'Flutter', :path => ENV['FLUTTER_FRAMEWORK_DIR']
  
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
    end
  end
end
