platform :ios, '14.0'

ENV['COCOAPODS_DISABLE_STATS'] = 'true'

use_frameworks!

target 'Runner' do
  # Flutter Pod dependencies
  project '../ios/Runner', {
    'Debug' => :debug,
    'Profile' => :release,
    'Release' => :release,
  }

  # Flutter pods
  pod 'Flutter', :path => '../flutter/bin/cache/artifacts/engine/ios'
  
  # Flutter application pods
  flutter_application_path = '../'
  load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')
end
